### ISSUE TITLE
Syntax errors

### ISSUE THREAD

**Issue by easystudios** [stripe/stripe-connect-rocketrides#11]
I am having issues with syntax .
while running this demo app , it constanlty keeps on giving syntax errors and does not run at all.
This is the log : 
router.get('/dashboard', pilotRequired, async (req, res) => {
                                              ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/colworx/Downloads/stripe-connect-rocketrides-master/server/app.js:52:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

**Comment by Fahrenheit-sp** [comment]
@easystudios +1. Got the same issue.

**Comment by romain-stripe** [comment]
Sorry you ran into this @easystudios, and thanks @Fahrenheit-sp for helping out! I think this was indeed due to `async`/`await` not be available on the Node version you were using.

I'm going to close this issue now but feel free to reopen if you're still encountering troubles when running this app. Thanks!
